---
title: "Dia 2 curso r"
output: html_notebook
---

## Lectura de datos en R


```{r}
# leer el archivo 1
read.table("datasets/penguins_matrix_space-delim.txt",
           h = TRUE)
```

```{r}
# leer en R el archivo penguins_matrix1.txt
read.delim("datasets/penguins_matrix1.txt")
```

```{r}
# leer en R el archivo penguins_matrix2.txt
read.csv("datasets/penguins_matrix2.txt")
```

```{r}
# leer en R el archivo penguins_matrix3.txt
datos_pinguinos <- read.csv2("datasets/penguins_matrix3.txt")
datos_pinguinos
```


## Bajar datos de internet

```{r}
# Especificar la URL donde se almacena el archivo
url <- "https://www.stats.govt.nz/assets/Uploads/Annual-enterprise-survey/Annual-enterprise-survey-2017-financial-year-provisional/Download-data/annual-enterprise-survey-2017-financial-year-provisional-csv.csv"

destfile <- "datasets/datos_de_internet.csv"

download.file(url, destfile)
```

# hacer subconjuntos de un data frame

```{r}
datos_pinguinos[ , 3]
str(datos_pinguinos)
```

# eliminar una columna o fila
```{r}
datos_pinguinos_limpios <- datos_pinguinos[c(4,8,23:30) , 4:6 ]
write.table(datos_pinguinos_limpios,
            "datasets/matriz_pinguinos_limpia.txt",
            quote = F,
            sep = "\t",
            row.names = F)
```


# subconjunto por nombre

```{r}
datos_pinguinos$bill_length_mm
```

```{r}
datos_pinguinos[ , c("island", "bill_length_mm")]
```

### subconjunto por condición

```{r}
nrow(datos_pinguinos)

nrow(datos_pinguinos[datos_pinguinos$species == "Gentoo", ])
```

```{r}
datos_pinguinos[datos_pinguinos$species != "Gentoo", ]
```

```{r}
#filtro por dos condiciones
datos_pinguinos[datos_pinguinos$species == "Gentoo" |
                  datos_pinguinos$species == "Adelie", ]

```

```{r}
#filtro por dos condiciones
datos_pinguinos[datos_pinguinos$species != "Gentoo" &
                  datos_pinguinos$bill_length_mm > 40, ]
```

```{r}
## ejercicio 4a,b
datos_ping_subset1<- datos_pinguinos[ datos_pinguinos$sex == "female" &
                   datos_pinguinos$year == 2009 &
                   datos_pinguinos$body_mass_g >= 3000, ]
nrow(datos_ping_subset1)
```

```{r}
#ejercicio 4c
datos_ping_subset4c<- datos_pinguinos[ datos_pinguinos$sex == "female" &
                   datos_pinguinos$year == 2009 &
                   datos_pinguinos$body_mass_g >= 3000, c("species",
                                                          "island")]
datos_ping_subset4c
```
```{r}
# Ejercicio 4d
datos_ping_subset4d <- datos_pinguinos[datos_pinguinos$sex == "male" &
                  datos_pinguinos$island == "Biscoe" &
                  datos_pinguinos$flipper_length_mm <= 190, ]

unique(datos_ping_subset4d[,"year"])
summary(datos_ping_subset4d)
```

```{r}
# hacer subconjunto de datos con la función subset()
datos_ping_depth <- subset(datos_pinguinos,
                           bill_depth_mm >= 17.15)
datos_ping_depth
```
```{r}
datos_ping_depth_dream <- subset(x = datos_ping_depth,
                                 subset = island == "Dream",
                                 select = c("species",
                                            "body_mass_g"))
datos_ping_depth_dream
```

## Modificar data frame
```{r}
# nueva columna de la relación alto/largo del pico
datos_pinguinos$Rel_bill_length_depth <- datos_pinguinos$bill_length_mm / datos_pinguinos$bill_depth_mm
datos_pinguinos
```

```{r}
# lo mismo de arriba con la función transform()
datos_pinguinos <- transform(datos_pinguinos,
                             Rel_bill_length_depth2 = 
                               bill_length_mm / bill_depth_mm)

datos_pinguinos
```

```{r}
# cambiar unidades de la variable masa corporal
datos_pinguinos$body_mass_kg <- datos_pinguinos$body_mass_g / 1000

datos_pinguinos[, c("body_mass_g", "body_mass_kg")]
```

```{r}
datos_pinguinos$mass_length <- datos_pinguinos$body_mass_g / datos_pinguinos[1 ,"bill_length_mm"]

datos_pinguinos
```
# Datos faltantes
```{r}
vec1 <- c(1,5,8,NA,4)
vec1
```

```{r}
is.na(vec1)
```

```{r}
# datos faltantes en un data frame
df <- data.frame(col1 = c(1:3, NA),
                 col2 = c("esto", "es", NA, "texto"),
                 col3 = c(T, F, T, T),
                 col4 = c(2.5, 4.2, 3.2, NA))
df
is.na(df)
is.na(df$col1)
is.na.data.frame(df)
```
```{r}
which(is.na(vec1))
```

```{r}
sum(is.na(vec1))
sum(is.na(df))
```

```{r}
colSums(is.na(df))
```

### Recodificación de los datos faltantes

```{r}
df <- data.frame(col1 = c(1:3, -999),
                 col2 = c(2.5, 4.2, -999, 3.2))
is.na(df)

```
```{r}
df[df == -999] <- NA
is.na(df)
```
```{r}
# remover todos los datos faltantes
df_complete <- na.omit(df)
df_complete
```
```{r}

```














